### ISSUE TITLE
Catch Python errors and send last line to Max

### ISSUE THREAD

**Issue by omarcostahamido** [iccmr-quantum/OSC-Qasm#15]
Here is a fun challenge @Itaborala :
When something goes terribly wrong in `osc_qasm.py` and it crashes, it prints to the terminal window, but the oblivious Max user won't know anything has happened unless the terminal window is open and visible. So, my question is: how would you catch the python error and send a message to Max saying "something went terribly wrong, osc_qasm.py says .... {_insert last error message here_}"

it would have to use something similar to what we already have at some point, for example:
`client.send_message("error", "You need to start osc_qasm.py with the following arguments: --token (--hub, --group, --project).")`

**Comment by Itaborala** [comment]
Pull Request #28 solves this Issue.
