### ISSUE TITLE
Websocket version?

### ISSUE THREAD

**Issue by petethomasmusique** [iccmr-quantum/OSC-Qasm#24]
Does Python have the ability to send / receive data via websockets? Browsers cannot send OSC directly. Instead they usually have to connect to a Node server via a websocket, and then the server sends OSC on its behalf.

Rather than doing this, if a python server could connect with a browser via a websocket this could be sidestepped. [this package](https://pypi.org/project/websockets/#history) suggests that this is possible and is being actively maintained.

**Comment by omarcostahamido** [comment]
This is going to lead to a spinoff of OSC-Qasm, the _Websocket-Qasm_!

**Comment by Itaborala** [comment]
@omarcostahamido
Even with a possible spinoff Websocket-Qasm (nice idea!) Wouldn't it be interesting to have some websocket fallback/integration/flag in OSC-Qasm as well, for cross applications?

Example: web app sends qasm code to IMBQ, and the results are sent to Max.

Or Maybe the future spinoff websocket_qasm.py could be imported to osc_qasm.py or something. In any case, I think it would be great to have them talk with each other!

**Comment by omarcostahamido** [comment]
@Itaborala super! love the idea of cross application talk. My only concern is if it would possibly slow down the system to have those multiple channels open at the same time. As it is right now, there is nothing stopping the user to change the ports on osc_qasm.py so that it listens on a port that app A is sending to, but it will reply back on a port that app B is listening to.

**Comment by omarcostahamido** [comment]
@petethomasmusique 
> _(...)_ Browsers cannot send OSC directly.

I was talking with @Itaborala and he just dropped this [osc-js link](https://www.npmjs.com/package/osc-js), haven't opened to explore, but maybe it could be helpful in your experiments.

**Comment by petethomasmusique** [comment]
Thanks @omarcostahamido. Yes. most useful thanks. I've implemented this before with success, but requires a node server to listen out for ws messages from the browser, which then translates this to a nicely formatted osc message. It's probably the simplest implementation, and would sidestep having to rewrite OSC-Qasm, but doesn't solve the issue of sending osc directly from the browser.

**Comment by omarcostahamido** [comment]
Spinoff repo created [here](https://github.com/iccmr-quantum/SOC-Qasm). Y'all must have received invitation to join it. When we get to release 1 there, I'll close this issue.

**Comment by omarcostahamido** [comment]
@petethomasmusique @Itaborala 
I've finished drafting a socket.io version [here](https://github.com/iccmr-quantum/SOC-Qasm).
Feel free to try this and leave some feedback.
As usual, I provide the max version of doing this... but you're invited to write a client in the context of a web browser.
Please refer to the [socket.io documentation](https://socket.io/docs/v4/client-installation/) for more details.

**Comment by omarcostahamido** [comment]
As of [this moment](https://github.com/iccmr-quantum/SOC-Qasm/pull/5) there is the web browser client example for SOC-Qasm. I'm closing this issue now. Feel free to create another spinoff for vanilla websockets if you must.
