### ISSUE TITLE
Add Pd client

### ISSUE THREAD

**Issue by Itaborala** [iccmr-quantum/OSC-Qasm#35]
Just something to consider: Max is the offered client in this repo, but in reality any application making use of OSC and respecting the (_osc-qasm_) protocol can serve as client (both C1 and C2) really...

(maybe should copy this comment somewhere else so that we can keep discussing this)

_Originally posted by @omarcostahamido in https://github.com/iccmr-quantum/OSC-Qasm/pull/34#discussion_r844090036_

**TODO**
- [x] create Pd client

**Comment by Itaborala** [comment]
Responding the comment in this new issue: We could rethink how to approach this clients in the documentation, in a more generalized way. Then, we could have an "examples" and/or "clients" folder, in which we could add several clients in the future as we test, compatibilize and increase this project.

**Comment by omarcostahamido** [comment]
We will close this issue when we have a couple more clients and decide to pull the plug in reorganizing the folder structure.
For right now I'll just edit the OP to include a tasklist.

**Comment by omarcostahamido** [comment]
splitting this task into 2 since Pd client will come out with version 2.0.0 and Supercollider client will come out late.
