### ISSUE TITLE
`--help` description for `--headless` is wrong

### ISSUE THREAD

**Issue by Itaborala** [iccmr-quantum/OSC-Qasm#38]
When running `osc_qasm.exe --help` , it shows and describes all of the arguments. However, the description for the `--headless` flag is incorrect: it has two additional sentences that were actually copied from the previous flag, `--remote`.

To solve:

- [x]  Remove the last two sentences from the `--headless` description at osc_qasm.py (line 242)

**Comment by omarcostahamido** [comment]
fixed in 9b32edae6f8dc765a52c0a05728e8db7c35461ef but now still requires compiling everything again.
