### ISSUE TITLE
Add macos-arm application version

### ISSUE THREAD

**Issue by omarcostahamido** [iccmr-quantum/OSC-Qasm#41]
not sure `eel` and `pyinstaller` are ready for it. But I guess I can try (at least for one version).

**Comment by omarcostahamido** [comment]
If and when either me or ICCMR gets access to an M1 machine, we can resolve this issue and release `v2.2.0`.

**Comment by Itaborala** [comment]
Just found out that Hari, the new ICCMR Research Assistant, has an M1 machine! I'll make an attempt this week.

**Comment by Itaborala** [comment]
Since I'm also working on Issue #47 today (at this [new branch](../tree/customfunc)), maybe it's an opportunity to reach v2.2.0?
